/**
 * items.js —— 装备数据
 * 字段说明：
 *   id       装备唯一标识
 *   name     装备名
 *   category 分类：物理 / 法术 / 防御 / 游走 / 打野 / 攻速暴击
 *   tag      附加标签（如 移动 / 鞋子）
 *   price    价格（金币）
 *   stats    属性列表
 *   passives 被动效果 [{name, desc}]
 *   active   主动效果 {name, desc} 或 null
 *   compose  合成路径（前置组件名）
 *   heroes   适配英雄（id 数组）
 *   when     适用场景说明
 */
window.WQK = window.WQK || {};

window.WQK.items = [
  /* =============== 攻速暴击 =============== */
  { id:"wujinzhanren", name:"无尽战刃", category:"攻速暴击", tag:"暴击核心", price:2140,
    stats:["+100 物理攻击","+20% 暴击率"],
    passives:[{ name:"无尽", desc:"暴击效果提升 40%，暴击体系的核心装备。" }],
    active:null, compose:["风暴巨剑","冲能拳套"], heroes:["houyi","sunshangxiang","sunwukong","luban7"],
    when:"所有暴击流射手/打野的必出核心，无尽成型即伤害质变。" },
  { id:"yingren", name:"影刃", category:"攻速暴击", tag:"攻速", price:2070,
    stats:["+30% 攻击速度","+25% 暴击率","+5% 移速"],
    passives:[{ name:"影炎", desc:"暴击后提升 25% 攻速与 10% 移速，持续 2 秒。" }],
    active:null, compose:["雷鸣刃","匕首"], heroes:["houyi","luban7","jialuo","huangzhong"],
    when:"站桩射手的攻速暴击第二件，配合无尽收益最大化。" },
  { id:"zongshizhili", name:"宗师之力", category:"攻速暴击", tag:"强击", price:2100,
    stats:["+60 物理攻击","+20% 暴击率","+400 最大生命","+400 最大法力"],
    passives:[{ name:"强击", desc:"使用技能后 5 秒内下一次普攻额外造成 80% 攻击力的物理伤害。" }],
    active:null, compose:["光辉之剑","日冕"], heroes:["sunshangxiang","nakelulu","sunwukong","yao"],
    when:"技能接普攻型英雄（孙尚香、露露）的核心，一击爆发质变。" },
  { id:"poxiao", name:"破晓", category:"攻速暴击", tag:"射手神装", price:3400,
    stats:["+50 物理攻击","+35% 攻击速度","+15% 暴击率","+10% 移速"],
    passives:[{ name:"破甲", desc:"远程英雄物理穿透提升至 40%，近战减半。" }],
    active:null, compose:["碎星锤","穿云弓"], heroes:["houyi","luban7","marke","direnje","jialuo"],
    when:"射手后期终极神装，打前排坦克的答案，输出直接跨档。" },
  { id:"shandianbishou", name:"闪电匕首", category:"攻速暴击", tag:"攻速", price:1800,
    stats:["+35% 攻击速度","+15% 暴击率","+8% 移速"],
    passives:[{ name:"电弧", desc:"普攻有 30% 概率触发闪电链，对周围敌人造成法术伤害。" }],
    active:null, compose:["匕首","风暴巨剑"], heroes:["houyi","luban7","geya","mengya"],
    when:"前期性价比极高的攻速装，清线刷野效率高。" },
  { id:"zhurizhigong", name:"逐日之弓", category:"攻速暴击", tag:"主动爆发", price:2100,
    stats:["+25% 攻击速度","+15% 暴击率","+5% 移速"],
    passives:[{ name:"被动·精准", desc:"普攻附带额外物理伤害。" }],
    active:{ name:"逐日", desc:"提升自身 25% 射程与 15% 移速，持续 5 秒。" },
    compose:["穿云弓","冲能拳套"], heroes:["houyi","jialuo","huangzhong","direnje"],
    when:"站桩射手提升输出环境，开逐日风筝打肉一绝。" },

  /* =============== 物理 =============== */
  { id:"anyingzhanshou", name:"暗影战斧", category:"物理", tag:"战士核心", price:2140,
    stats:["+85 物理攻击","+15% 冷却缩减","+500 最大生命"],
    passives:[{ name:"切割", desc:"对英雄造成伤害时降低其护甲，叠满 5 层减少 170 点护甲。" },{ name:"残废", desc:"技能命中后降低目标 20% 移速，持续 2 秒。" }],
    active:null, compose:["陨星","日冕"], heroes:["lvbu","kai","yase","dianwei","hanxin"],
    when:"战士/刺客的通用核心装，穿透+冷却+血量三合一，前中期强势。" },
  { id:"pojun", name:"破军", category:"物理", tag:"大后期", price:2990,
    stats:["+180 物理攻击"],
    passives:[{ name:"破军", desc:"对生命值低于 50% 的目标额外造成 30% 伤害。" }],
    active:null, compose:["风暴巨剑","风暴巨剑"], heroes:["lvbu","huamulan","kai","gongbenwuzang"],
    when:"大后期输出装，收割残血与打坦都有奇效，价格昂贵前期慎出。" },
  { id:"suixingchui", name:"碎星锤", category:"物理", tag:"穿透", price:2100,
    stats:["+80 物理攻击","+10% 冷却缩减"],
    passives:[{ name:"破甲", desc:"获得 40% 物理穿透。" }],
    active:null, compose:["陨星","铁剑"], heroes:["lvbu","huamulan","dianwei","damo"],
    when:"对手前排护甲成型时必备，替代暗影战斧的打坦利器。" },
  { id:"qixiezhiren", name:"泣血之刃", category:"物理", tag:"吸血", price:1740,
    stats:["+100 物理攻击","+25% 物理吸血"],
    passives:[], active:null, compose:["铁剑","吸血之镰"], heroes:["houyi","libai","marke","luban7"],
    when:"物理英雄续航装，刷野带线回血不回家。" },
  { id:"zhicairzhiren", name:"制裁之刃", category:"物理", tag:"吸血", price:1800,
    stats:["+100 物理攻击","+15% 物理吸血"],
    passives:[{ name:"制裁", desc:"普攻命中减少目标 50% 生命回复与吸血，持续 3 秒。" }],
    active:null, compose:["吸血之镰","铁剑"], heroes:["houyi","luban7","marke"],
    when:"对面有程咬金/蔡文姬/貂蝉等回复英雄时的针对性出装。" },
  { id:"binghenzhiwo", name:"冰痕之握", category:"物理", tag:"强击", price:2100,
    stats:["+500 最大生命","+400 最大法力","+10% 冷却缩减","+30 物理防御"],
    passives:[{ name:"强击", desc:"技能后下一次普攻造成范围减速，留人神技。" }],
    active:null, compose:["光辉之剑","布甲"], heroes:["yase","sunce","lianpo","laofuzi"],
    when:"战士半肉控制流，技能黏人打拉扯，边路带线舒服。" },
  { id:"mingdaosiming", name:"名刀·司命", category:"物理", tag:"保命", price:1500,
    stats:["+60 物理攻击","+5% 冷却缩减"],
    passives:[{ name:"名刀", desc:"受到致命伤害后进入 1 秒无敌并加移速（内置 CD）。" }],
    active:null, compose:["铁剑","布甲"], heroes:["kai","huamulan","libai","sunwukong"],
    when:"切C刺客必备的保命装，关键时刻一秒钟反杀。" },
  { id:"xuemonuzhi", name:"血魔之怒", category:"物理", tag:"保命", price:2120,
    stats:["+1000 最大生命","+20 物理攻击"],
    passives:[{ name:"血怒", desc:"生命值低于 30% 时获得一个随攻击力提升的护盾，持续 5 秒。" }],
    active:null, compose:["红宝石","铁剑"], heroes:["dianwei","kai","yase","niumo"],
    when:"半肉战士的残血反杀装，配合被动免伤能抗住一波爆发。" },
  { id:"chunjingcangqiong", name:"纯净苍穹", category:"物理", tag:"减伤", price:2120,
    stats:["+100 物理攻击","+10% 冷却缩减","+500 最大生命"],
    passives:[{ name:"残废", desc:"技能命中减少目标 20% 移速。" }],
    active:{ name:"驱散", desc:"受到的伤害减少 30%，持续 1.5 秒。" },
    compose:["风暴巨剑","布甲"], heroes:["houyi","marke","dianwei","yase"],
    when:"射手/战士对抗刺客突进的保命装，开启瞬间减伤反打。" },
  { id:"moshou", name:"末世", category:"物理", tag:"攻速", price:2160,
    stats:["+60 物理攻击","+30% 攻击速度","+10% 物理吸血"],
    passives:[{ name:"破败", desc:"普攻附带目标当前生命值 8% 的物理伤害。" }],
    active:null, compose:["速击之枪","吸血之镰"], heroes:["marke","houyi","gongsunli","luban7"],
    when:"攻速射手打坦神器，马克波罗的核心装，百分比伤害通吃一切。" },

  /* =============== 法术 =============== */
  { id:"huixiangzhizhang", name:"回响之杖", category:"法术", tag:"法强", price:2100,
    stats:["+240 法术攻击","+7% 移速"],
    passives:[{ name:"回响", desc:"技能命中触发小范围爆炸，造成额外法术伤害（5 秒 CD）。" }],
    active:null, compose:["大棒","大棒"], heroes:["daji","xiaoqiao","zhugeliang","anqila"],
    when:"法师通用第一件，爆发与机动兼顾，清线消耗舒服。" },
  { id:"boxuezhenu", name:"博学者之怒", category:"法术", tag:"法强核心", price:2300,
    stats:["+260 法术攻击"],
    passives:[{ name:"毁灭", desc:"法术攻击提升 30%，法师伤害质变的核心装。" }],
    active:null, compose:["大棒","大棒","大棒"], heroes:["daji","anqila","xiaoqiao","zhugeliang"],
    when:"所有爆发法师的必出核心，帽子一出伤害翻倍。" },
  { id:"xuwufazhang", name:"虚无法杖", category:"法术", tag:"法穿", price:2110,
    stats:["+180 法术攻击","+10% 冷却缩减"],
    passives:[{ name:"破魔", desc:"获得 45% 法术穿透。" }],
    active:null, compose:["大棒","咒术典籍"], heroes:["daji","anqila","wangzhaojun","zhugeliang"],
    when:"对面魔抗成型时的法穿装，法师打坦必备。" },
  { id:"tongkumianju", name:"痛苦面具", category:"法术", tag:"持续", price:2040,
    stats:["+120 法术攻击","+5% 冷却缩减","+500 最大生命"],
    passives:[{ name:"折磨", desc:"技能命中造成目标当前生命值 3% 的持续法术伤害。" }],
    active:null, compose:["大棒","红宝石"], heroes:["zhouyu","bianque","shangguanwaner","miyue"],
    when:"持续输出型法师（周瑜/扁鹊）的核心，打肉磨血极强。" },
  { id:"xianzheshushu", name:"贤者之书", category:"法术", tag:"大后期", price:2990,
    stats:["+400 法术攻击"],
    passives:[{ name:"刻印", desc:"技能对英雄造成额外法术伤害。" }],
    active:null, compose:["大棒","大棒","大棒"], heroes:["daji","anqila","xiaoqiao","wuzetian"],
    when:"法师大后期终极装，法强拉满，一技能即秒人。" },
  { id:"shishenzhishu", name:"噬神之书", category:"法术", tag:"吸血", price:2090,
    stats:["+180 法术攻击","+800 最大生命"],
    passives:[{ name:"血族", desc:"获得 25% 法术吸血。" }],
    active:null, compose:["血族之书","大棒"], heroes:["diaochan","zhugeliang","gaojianli","shangguanwaner"],
    when:"持续作战法师的续航核心，貂蝉、诸葛亮贴脸起舞之本。" },
  { id:"shengbei", name:"圣杯", category:"法术", tag:"回蓝", price:1900,
    stats:["+180 法术攻击","+15% 冷却缩减","+1000 最大法力"],
    passives:[{ name:"澜动", desc:"每秒回复法力，法力全满时转为回复生命。" }],
    active:null, compose:["破碎圣杯","咒术典籍"], heroes:["wangzhaojun","caiwenji","zhouyu","sunbin"],
    when:"续航型法师/辅助神装，永动机般不用回家。" },
  { id:"mengyanzhiya", name:"梦魇之牙", category:"法术", tag:"克制", price:2050,
    stats:["+180 法术攻击","+5% 冷却缩减","+500 最大生命"],
    passives:[{ name:"制裁", desc:"技能命中减少目标 50% 生命回复与吸血，持续 3 秒。" }],
    active:null, compose:["大棒","红宝石"], heroes:["wangzhaojun","daji","anqila","zhouyu"],
    when:"对面有强回复英雄（程咬金/蔡文姬/芈月）时的针对性出装。" },
  { id:"shizhiyuyan", name:"时之预言", category:"法术", tag:"半肉", price:2090,
    stats:["+160 法术攻击","+800 最大生命","+800 最大法力"],
    passives:[{ name:"守护", desc:"每点法强转化为 0.6 双抗，最高 250 点（版本以实际为准）。" }],
    active:null, compose:["大棒","红宝石"], heroes:["diaochan","change","caiwenji","miyue"],
    when:"半肉法坦出装，貂蝉/嫦娥站得住的资本。" },
  { id:"huiyue", name:"辉月", category:"法术", tag:"保命", price:1990,
    stats:["+160 法术攻击","+10% 冷却缩减"],
    passives:[], active:{ name:"月之守护", desc:"进入 1.5 秒无敌状态（无法移动），冷却 90 秒。" },
    compose:["大棒","咒术典籍"], heroes:["diaochan","shangguanwaner","zhugeliang","daji"],
    when:"法师保命神装，被切时金身躲伤害等队友支援。" },
  { id:"wushufazhang", name:"巫术法杖", category:"法术", tag:"强击", price:2070,
    stats:["+180 法术攻击","+5% 移速"],
    passives:[{ name:"强击", desc:"使用技能后下一次普攻附带 30% 法强的法术伤害。" }],
    active:null, compose:["光辉之剑","大棒"], heroes:["yixing","milaidi","bianque","sikongzhen"],
    when:"技能接普攻型法师的核心，攻速法伤流（如弈星）必备。" },
  { id:"huangjinshengjian", name:"黄金圣剑", category:"法术", tag:"攻速法伤", price:2070,
    stats:["+35% 攻击速度","+150 法术攻击","+5% 冷却缩减"],
    passives:[{ name:"圣剑", desc:"普攻附带法术伤害，攻速越高收益越大。" }],
    active:null, compose:["魅影面罩","咒术典籍"], heroes:["luna","miyue","ailin","sikongzhen"],
    when:"露娜/芈月等普攻型法师的核心，平A也能打满输出。" },
  { id:"chirezhizhe", name:"炽热支配者", category:"法术", tag:"保命", price:1800,
    stats:["+160 法术攻击","+10% 冷却缩减"],
    passives:[], active:{ name:"炽热", desc:"血量低于 30% 时自动解除控制并获得护盾与加速。" },
    compose:["咒术典籍","红宝石"], heroes:["daji","anqila","zhenji"],
    when:"手短法师的保命装，被刺客贴脸时自动解控逃生。" },

  /* =============== 防御 =============== */
  { id:"hongliandoupeng", name:"红莲斗篷", category:"防御", tag:"灼烧", price:2000,
    stats:["+500 最大生命","+90 物理防御"],
    passives:[{ name:"献祭", desc:"每秒对周围敌人造成法术伤害（随生命值成长）。" }],
    active:null, compose:["布甲","红宝石"], heroes:["xiangyu","chengyaojin","dianwei","zhubajie"],
    when:"坦克边路的第一件，清线快+范围灼烧，对拼占优。" },
  { id:"buxiangzhengzhao", name:"不祥征兆", category:"防御", tag:"克制攻速", price:2180,
    stats:["+1200 最大生命","+270 物理防御"],
    passives:[{ name:"寒铁", desc:"受到普攻时降低攻击者 30% 攻速与 15% 移速，持续 3 秒。" }],
    active:null, compose:["布甲","布甲","红宝石"], heroes:["xiangyu","zhangfei","niumo","baiqi"],
    when:"克制射手攻速流，前排抗伤打团必出。" },
  { id:"jihanfengbao", name:"极寒风暴", category:"防御", tag:"冷却", price:2100,
    stats:["+20% 冷却缩减","+500 最大法力","+360 物理防御"],
    passives:[{ name:"冰心", desc:"单次受伤害超过 10% 生命时触发冰爆，对周围敌人减速并造成伤害。" }],
    active:null, compose:["布甲","布甲"], heroes:["xiangyu","lianpo","baiqi","daqiao"],
    when:"依赖冷却的坦克/辅助装，配合技能流打法收益高。" },
  { id:"monvdoupeng", name:"魔女斗篷", category:"防御", tag:"法抗", price:2080,
    stats:["+1000 最大生命","+200 法术防御"],
    passives:[{ name:"迷雾", desc:"脱战 5 秒后获得一个随等级成长的魔法护盾。" }],
    active:null, compose:["抗魔披风","红宝石"], heroes:["zhangfei","niumo","baiqi","kai"],
    when:"对面法师爆发高时的必备魔抗装，护盾能挡一套。" },
  { id:"businiiaozhiyan", name:"不死鸟之眼", category:"防御", tag:"回复", price:2100,
    stats:["+1200 最大生命","+240 法术防御"],
    passives:[{ name:"复苏", desc:"生命值越低，受到的回复效果越强（最高 40%）。" }],
    active:null, compose:["抗魔披风","红宝石"], heroes:["chengyaojin","zhubajie","baiqi","sulie"],
    when:"高回复坦克（程咬金/猪八戒）的核心，残血回血离谱。" },
  { id:"fanshangjia", name:"反伤刺甲", category:"防御", tag:"反伤", price:1950,
    stats:["+400 最大生命","+420 物理防御"],
    passives:[{ name:"荆棘", desc:"受到物理伤害时对攻击者反弹伤害，并降低其吸血效果。" }],
    active:null, compose:["布甲","布甲"], heroes:["dianwei","lvbu","xiangyu","kai"],
    when:"克制物理战士与刺客，贴身肉搏反伤拉满。" },
  { id:"bazhezhongzhuang", name:"霸者重装", category:"防御", tag:"大血", price:2070,
    stats:["+2000 最大生命"],
    passives:[{ name:"复苏", desc:"脱战 5 秒后每秒回复 4% 最大生命。" }],
    active:null, compose:["红宝石","红宝石"], heroes:["chengyaojin","baiqi","zhubajie"],
    when:"纯肉坦克的终极血装，团战进场吸收成吨伤害。" },
  { id:"baoliezhiyi", name:"暴烈之甲", category:"防御", tag:"反打", price:2100,
    stats:["+900 最大生命","+220 物理防御"],
    passives:[{ name:"无畏", desc:"每次受击提升 2% 伤害与 1% 移速，最多叠 5 层。" }],
    active:null, compose:["布甲","红宝石"], heroes:["kai","dianwei","yase","laofuzi"],
    when:"战士半肉反打装，越打越强，适合贴脸持续作战英雄。" },
  { id:"xianzhedebi", name:"贤者的庇护", category:"防御", tag:"复活甲", price:2080,
    stats:["+140 物理防御","+140 法术防御"],
    passives:[{ name:"复生", desc:"死亡后 2 秒内原地复活并获得部分生命（每局最多触发 2 次）。" }],
    active:null, compose:["布甲","抗魔披风"], heroes:["houyi","sunwukong","kai","xiaoqiao"],
    when:"大后期保命神装，团战多一条命，C位必备。" },
  { id:"jisuzhanxue", name:"急速战靴", category:"防御", tag:"移动", price:710,
    stats:["+30% 攻击速度"],
    passives:[], active:null, compose:["鞋子"], heroes:["houyi","luban7","marke","jialuo"],
    when:"攻速射手的首选鞋，前期清线手感好。" },
  { id:"dikangzhixue", name:"抵抗之靴", category:"防御", tag:"移动", price:710,
    stats:["+110 法术防御"],
    passives:[{ name:"韧性", desc:"获得 35% 韧性（减少被控时间）。" }],
    active:null, compose:["鞋子"], heroes:["lvbu","kai","dianwei","huamulan"],
    when:"被控多的对抗位/打野首选，减少被控时间就是救命。" },
  { id:"lengjingzhixue", name:"冷静之靴", category:"防御", tag:"移动", price:710,
    stats:["+15% 冷却缩减"],
    passives:[], active:null, compose:["鞋子"], heroes:["zhugeliang","caiwenji","wangzhaojun"],
    when:"依赖技能CD的法师与辅助，技能转得快就有用。" },
  { id:"yingrenzhizu", name:"影忍之足", category:"防御", tag:"移动", price:710,
    stats:["+110 物理防御"],
    passives:[{ name:"物理减免", desc:"受到普攻伤害时减少 15% 物理伤害。" }],
    active:null, compose:["鞋子"], heroes:["xiangyu","baiqi","laofuzi"],
    when:"对线射手/战士的肉坦鞋，普攻减伤直接。" },
  { id:"mifazhixue", name:"秘法之靴", category:"防御", tag:"移动", price:710,
    stats:["+75 法术穿透"],
    passives:[], active:null, compose:["鞋子"], heroes:["daji","anqila","diaochan"],
    when:"爆发法师前期的穿透鞋，中期伤害成型快。" },
  { id:"jibuzhixue", name:"疾步之靴", category:"防御", tag:"移动", price:710,
    stats:["+8% 移速"],
    passives:[{ name:"神行", desc:"脱战 5 秒后移速大幅提升。" }],
    active:null, compose:["鞋子"], heroes:["guiguzi","lanlingwang","machao"],
    when:"节奏型打野与支援辅助，游走抓人速度拉满。" },

  /* =============== 游走 =============== */
  { id:"jiyin", name:"极影", category:"游走", tag:"光环·攻速", price:1900,
    stats:["+20% 冷却缩减","+800 最大生命","+500 最大法力"],
    passives:[{ name:"游击", desc:"附近队友获得 20% 攻速与 10% 冷却缩减加成。" }],
    active:null, compose:["凤鸣指环","布甲"], heroes:["sunbin","zhangfei","caiwenji","daqiao"],
    when:"射手体系辅助的核心，提升全队输出频率。" },
  { id:"jinweirongyao", name:"近卫荣耀", category:"游走", tag:"光环·双抗", price:1900,
    stats:["+20% 冷却缩减","+800 最大生命","+500 最大法力"],
    passives:[{ name:"奉献", desc:"附近队友获得 30 点物理/法术防御加成。" }],
    active:null, compose:["凤鸣指环","抗魔披风"], heroes:["zhangfei","niumo","baiqi","lianpo"],
    when:"坦克辅助的核心，提升全队坦度，抗伤能力更强。" },
  { id:"benlangwenzhang", name:"奔狼纹章", category:"游走", tag:"主动加速", price:1900,
    stats:["+800 最大生命","+500 最大法力"],
    passives:[], active:{ name:"奔腾", desc:"周围队友获得大幅移速加成，持续 3 秒，追击逃跑都好用。" },
    compose:["凤鸣指环","布甲"], heroes:["guiguzi","sunbin","niumo"],
    when:"开团/追击型辅助的主动装，一波加速就是一波团战。" },
  { id:"jiushuzhiyi", name:"救赎之翼", category:"游走", tag:"主动护盾", price:1900,
    stats:["+800 最大生命","+500 最大法力"],
    passives:[], active:{ name:"救援", desc:"为周围生命值最低的队友提供护盾，关键时刻保命。" },
    compose:["凤鸣指环","布甲"], heroes:["caiwenji","zhangfei","yaoling"],
    when:"保人型辅助的核心，被切时护盾救下C位。" },
  { id:"xingquan", name:"星泉", category:"游走", tag:"主动分担", price:1900,
    stats:["+800 最大生命","+500 最大法力"],
    passives:[], active:{ name:"星之甘露", desc:"链接一名队友，为其分担部分伤害，回复其血量。" },
    compose:["凤鸣指环","布甲"], heroes:["caiwenji","yaoling","sangqi"],
    when:"强保C辅助的进阶装，贴身保护核心输出。" },
  { id:"xingzhaozhijian", name:"形昭之鉴", category:"游走", tag:"主动视野", price:1900,
    stats:["+800 最大生命","+500 最大法力"],
    passives:[], active:{ name:"觅形", desc:"探测周围视野并减速隐身单位，持续 4 秒。" },
    compose:["凤鸣指环","布甲"], heroes:["zhongkui","guiguzi","dunshan"],
    when:"对抗隐身/草丛英雄的视野装，防兰陵王阿轲突袭。" },

  /* =============== 打野 =============== */
  { id:"xunshoulifu", name:"巡守利斧", category:"打野", tag:"肉刀", price:1980,
    stats:["+1200 最大生命","+40 物理防御"],
    passives:[{ name:"狩猎", desc:"击杀野怪叠加生命，惩戒对野怪造成真实伤害。" }],
    active:null, compose:["狩猎宽刃","布甲"], heroes:["dianwei","zhaoyun","peiqinhu"],
    when:"半肉打野的首选打野刀，越刷越肉。" },
  { id:"tanlanzhishi", name:"贪婪之噬", category:"打野", tag:"红刀", price:2160,
    stats:["+60 物理攻击","+8% 冷却缩减","+8% 移速"],
    passives:[{ name:"狩猎", desc:"击杀野怪叠加攻击，惩戒对野怪造成真实伤害。" }],
    active:null, compose:["追击刀锋","铁剑"], heroes:["hanxin","sunwukong","libai","nakelulu"],
    when:"输出型刺客打野的首选，刷野快+伤害高。" },
  { id:"wenfudajian", name:"符文大剑", category:"打野", tag:"蓝刀", price:2160,
    stats:["+200 法术攻击","+15% 冷却缩减","+8% 移速"],
    passives:[{ name:"狩猎", desc:"击杀野怪叠加法强，惩戒对野怪造成真实伤害。" }],
    active:null, compose:["游击弯刀","大棒"], heroes:["luna","simayi","peiqinhu"],
    when:"法术打野（露娜/司马懿）的首选，法伤打野必备。" },
  { id:"yuhuozhinu", name:"浴火之怒", category:"打野", tag:"黄刀", price:1980,
    stats:["+1200 最大生命","+30 移速"],
    passives:[{ name:"狩猎", desc:"击杀野怪叠加生命与移速，惩戒对野怪造成真实伤害。" }],
    active:null, compose:["狩猎宽刃","布甲"], heroes:["chengyaojin","miyue","zhubajie"],
    when:"边路带惩戒的发育流打野刀，偷野发育单带两不误。" },

  /* =============== 新增装备 · 基础/进阶组件（数据库同步 2026.08） =============== */
  /* ---- 物理组件 ---- */
  { id:"tiejian", name:"铁剑", category:"物理", tag:"基础", price:250,
    stats:["+20 物理攻击"], passives:[], active:null, compose:[], heroes:[],
    when:"最基础的攻击组件，前期过渡与合成必备。" },
  { id:"xixuezhilian", name:"吸血之镰", category:"物理", tag:"基础", price:410,
    stats:["+10% 物理吸血"], passives:[], active:null, compose:[], heroes:[],
    when:"吸血类装备的基础组件。" },
  { id:"rimian", name:"日冕", category:"物理", tag:"组件", price:1030,
    stats:["+40 物理攻击","+200 最大生命","+5% 冷却缩减"],
    passives:[{ name:"残废", desc:"技能命中后降低目标移速。" }], active:null, compose:["铁剑","红玛瑙"], heroes:[],
    when:"暗影战斧等战士装的合成组件。" },
  { id:"yunxing", name:"陨星", category:"物理", tag:"组件", price:1080,
    stats:["+45 物理攻击","+10% 冷却缩减"],
    passives:[{ name:"切割", desc:"造成伤害时降低目标护甲。" }], active:null, compose:["铁剑","铁剑"], heroes:[],
    when:"暗影战斧/碎星锤的穿透组件。" },
  { id:"chuanyungong", name:"穿云弓", category:"物理", tag:"组件", price:1100,
    stats:["+30 物理攻击","+10% 攻击速度"],
    passives:[{ name:"精准", desc:"普攻附带额外物理伤害。" }], active:null, compose:["铁剑","匕首"], heroes:[],
    when:"逐日之弓/破晓的射手组件。" },
  { id:"guanghuizhijian", name:"光辉之剑", category:"物理", tag:"组件", price:950,
    stats:["+60 物理攻击","+200 最大法力"],
    passives:[{ name:"强击", desc:"使用技能后强化下一次普攻。" }], active:null, compose:["铁剑","蓝宝石"], heroes:[],
    when:"宗师之力/巫术法杖的强击组件。" },
  { id:"fengbaojujian", name:"风暴巨剑", category:"物理", tag:"组件", price:910,
    stats:["+80 物理攻击"], passives:[], active:null, compose:["铁剑","铁剑"], heroes:[],
    when:"破军/无尽战刃等大剑的合成组件。" },
  { id:"leimingren", name:"雷鸣刃", category:"物理", tag:"组件", price:730,
    stats:["+60 物理攻击"], passives:[], active:null, compose:["铁剑","铁剑"], heroes:[],
    when:"影刃等攻速暴击装的攻击组件。" },

  /* ---- 攻速暴击组件 ---- */
  { id:"bishou", name:"匕首", category:"攻速暴击", tag:"基础", price:290,
    stats:["+10% 攻击速度"], passives:[], active:null, compose:[], heroes:[],
    when:"攻速装的基础组件，前期过渡。" },
  { id:"bojiquantao", name:"搏击拳套", category:"攻速暴击", tag:"基础", price:320,
    stats:["+8% 暴击率"], passives:[], active:null, compose:[], heroes:[],
    when:"暴击装的基础组件。" },
  { id:"kuangbaoshuangren", name:"狂暴双刃", category:"攻速暴击", tag:"组件", price:890,
    stats:["+15% 攻击速度","+8% 暴击率"], passives:[], active:null, compose:["匕首","搏击拳套"], heroes:[],
    when:"影刃等攻速暴击装的组件。" },
  { id:"sujizhiqiang", name:"速击之枪", category:"攻速暴击", tag:"组件", price:890,
    stats:["+25% 攻击速度"],
    passives:[{ name:"精准", desc:"普攻附带额外物理伤害。" }], active:null, compose:["匕首","匕首"], heroes:[],
    when:"末世等攻速装的组件。" },
  { id:"chongnengquantao", name:"冲能拳套", category:"攻速暴击", tag:"组件", price:550,
    stats:["+15% 暴击率"], passives:[], active:null, compose:["搏击拳套"], heroes:[],
    when:"无尽战刃等暴击装的组件。" },

  /* ---- 防御组件 ---- */
  { id:"hongmanao", name:"红玛瑙", category:"防御", tag:"基础", price:300,
    stats:["+300 最大生命"], passives:[], active:null, compose:[], heroes:[],
    when:"生命类装备的基础组件。" },
  { id:"bujia", name:"布甲", category:"防御", tag:"基础", price:220,
    stats:["+90 物理防御"], passives:[], active:null, compose:[], heroes:[],
    when:"物理防御装的基础组件。" },
  { id:"kangmopifeng", name:"抗魔披风", category:"防御", tag:"基础", price:220,
    stats:["+90 法术防御"], passives:[], active:null, compose:[], heroes:[],
    when:"法术防御装的基础组件。" },
  { id:"tishenshuijing", name:"提神水晶", category:"防御", tag:"基础", price:140,
    stats:["+30% 回血率"], passives:[], active:null, compose:[], heroes:[],
    when:"续航类装备的基础组件。" },
  { id:"jingjihushou", name:"荆棘护手", category:"防御", tag:"组件", price:710,
    stats:["+160 物理防御","+30 物理攻击"],
    passives:[{ name:"荆棘", desc:"受到物理伤害时反弹部分伤害。" }], active:null, compose:["布甲","铁剑"], heroes:[],
    when:"反伤刺甲/暴烈之甲等半肉装的组件。" },
  { id:"shouhuzhezhikai", name:"守护者之铠", category:"防御", tag:"组件", price:730,
    stats:["+220 物理防御"],
    passives:[{ name:"寒铁", desc:"受到普攻时降低攻击者攻速。" }], active:null, compose:["布甲","布甲"], heroes:[],
    when:"不祥征兆/极寒风暴的物防组件。" },
  { id:"liliangyaodai", name:"力量腰带", category:"防御", tag:"组件", price:900,
    stats:["+700 最大生命"], passives:[], active:null, compose:["红玛瑙","红玛瑙"], heroes:[],
    when:"霸者重装等大血装的组件。" },
  { id:"shenyindoupeng", name:"神隐斗篷", category:"防御", tag:"组件", price:1020,
    stats:["+120 法术防御","+700 最大生命"], passives:[], active:null, compose:["抗魔披风","红玛瑙"], heroes:[],
    when:"魔女斗篷等法抗装的组件。" },
  { id:"shensuzhixue", name:"神速之靴", category:"防御", tag:"移动", price:250,
    stats:["+50 移动速度"], passives:[], active:null, compose:["鞋子"], heroes:[],
    when:"基础移动鞋，后续升级为各类功能鞋。" },

  /* ---- 法术组件 ---- */
  { id:"zhoushudianji", name:"咒术典籍", category:"法术", tag:"基础", price:300,
    stats:["+40 法术攻击"], passives:[], active:null, compose:[], heroes:[],
    when:"法强装的基础组件。" },
  { id:"lanbaoshi", name:"蓝宝石", category:"法术", tag:"基础", price:220,
    stats:["+300 最大法力"], passives:[], active:null, compose:[], heroes:[],
    when:"法力/回蓝装的基础组件。" },
  { id:"lianjinhufu", name:"炼金护符", category:"法术", tag:"基础", price:140,
    stats:["+25% 回蓝率"], passives:[], active:null, compose:[], heroes:[],
    when:"圣杯等回蓝装的组件。" },
  { id:"shengzhefadian", name:"圣者法典", category:"法术", tag:"组件", price:500,
    stats:["+40 法术攻击","+5% 冷却缩减"], passives:[], active:null, compose:["咒术典籍"], heroes:[],
    when:"冷却型法装的基础组件。" },
  { id:"yuansuzhang", name:"元素杖", category:"法术", tag:"组件", price:540,
    stats:["+80 法术攻击"], passives:[], active:null, compose:["咒术典籍","咒术典籍"], heroes:[],
    when:"回响之杖等法杖的组件。" },
  { id:"dabang", name:"大棒", category:"法术", tag:"组件", price:820,
    stats:["+120 法术攻击"], passives:[], active:null, compose:["元素杖"], heroes:[],
    when:"博学者之怒/虚无法杖等大棒的组件。" },
  { id:"meiyingmianzhao", name:"魅影面罩", category:"法术", tag:"组件", price:1020,
    stats:["+40 法术攻击","+300 最大生命"],
    passives:[{ name:"折磨", desc:"技能命中造成持续法术伤害。" }], active:null, compose:["咒术典籍","红玛瑙"], heroes:[],
    when:"痛苦面具等持续伤害装的组件。" },
  { id:"xuezuzhishu", name:"血族之书", category:"法术", tag:"组件", price:990,
    stats:["+80 法术攻击","+10% 法术吸血"], passives:[], active:null, compose:["咒术典籍","提神水晶"], heroes:[],
    when:"噬神之书等吸血法装的组件。" },
  { id:"posuishengbei", name:"破碎圣杯", category:"法术", tag:"组件", price:950,
    stats:["+80 法术攻击","+20% 回蓝率"], passives:[], active:null, compose:["圣者法典","炼金护符"], heroes:[],
    when:"圣杯的合成组件。" },
  { id:"yunlingmu", name:"云灵木", category:"法术", tag:"组件", price:800,
    stats:["+40 法术攻击","+5% 冷却缩减"], passives:[], active:null, compose:["咒术典籍","圣者法典"], heroes:[],
    when:"法强冷却装的基础组件。" },
  { id:"modaozhishi", name:"魔道之石", category:"法术", tag:"组件", price:900,
    stats:["+100 法术攻击"], passives:[], active:null, compose:["元素杖"], heroes:[],
    when:"回响之杖等法强装的组件。" },
  { id:"jinhuashuijing", name:"进化水晶", category:"法术", tag:"组件", price:720,
    stats:["+400 最大生命","+300 最大法力"], passives:[], active:null, compose:["红玛瑙","蓝宝石"], heroes:[],
    when:"时之预言等半肉法装的组件。" },

  /* ---- 打野组件 ---- */
  { id:"shoulliekuanren", name:"狩猎宽刃", category:"打野", tag:"组件", price:250,
    stats:["+30 物理攻击"],
    passives:[{ name:"狩猎", desc:"对野怪造成额外伤害，击杀野怪获得额外经验。" }], active:null, compose:[], heroes:[],
    when:"物理打野刀的基础组件。" },
  { id:"youjiwandao", name:"游击弯刀", category:"打野", tag:"组件", price:250,
    stats:["+30 法术攻击"],
    passives:[{ name:"狩猎", desc:"对野怪造成额外伤害，击杀野怪获得额外经验。" }], active:null, compose:[], heroes:[],
    when:"法术打野刀的基础组件。" },
  { id:"zhuijidaofeng", name:"追击刀锋", category:"打野", tag:"组件", price:300,
    stats:["+30 物理攻击"],
    passives:[{ name:"狩猎", desc:"对野怪造成额外伤害，击杀野怪获得额外经验。" }], active:null, compose:["狩猎宽刃"], heroes:[],
    when:"红刀（贪婪之噬）的前置组件。" },

  /* ---- 游走组件 ---- */
  { id:"xueshibaoshi", name:"学识宝石", category:"游走", tag:"组件", price:300,
    stats:["+5% 移动速度"],
    passives:[{ name:"奉献", desc:"不与队友分享小兵经济，额外获得金币。" }], active:null, compose:[], heroes:[],
    when:"辅助装的基础组件，保障辅助经济。" },
  { id:"fengzhiqingyu", name:"风之轻语", category:"游走", tag:"组件", price:500,
    stats:["+300 最大生命"], passives:[], active:null, compose:["学识宝石","红玛瑙"], heroes:[],
    when:"救赎之翼等保人辅助装的组件。" },
  { id:"fengmingzhihuan", name:"凤鸣指环", category:"游走", tag:"组件", price:500,
    stats:["+10% 冷却缩减"], passives:[], active:null, compose:["学识宝石","蓝宝石"], heroes:[],
    when:"极影等攻速冷却辅助装的组件。" },
  { id:"guwuzhidun", name:"鼓舞之盾", category:"游走", tag:"组件", price:500,
    stats:["+300 最大生命"], passives:[], active:null, compose:["学识宝石","布甲"], heroes:[],
    when:"近卫荣耀等双抗辅助装的组件。" },
  { id:"fenglingwenzhang", name:"风灵纹章", category:"游走", tag:"组件", price:500,
    stats:["+300 最大生命"], passives:[], active:null, compose:["学识宝石","布甲"], heroes:[],
    when:"奔狼纹章等主动加速辅助装的组件。" },

  /* =============== 新增装备 · 成品（数据库同步 2026.08） =============== */
  /* ---- 物理成品 ---- */
  { id:"tianqiong", name:"天穹", category:"物理", tag:"进阶保命", price:4080,
    stats:["+100 物理攻击","+15% 冷却缩减","+500 最大生命"],
    passives:[{ name:"残废", desc:"技能命中降低目标 20% 移速。" }],
    active:{ name:"天穹", desc:"解除控制并获得 40% 减伤，持续 3 秒。" },
    compose:["纯净苍穹","风暴巨剑"], heroes:["houyi","marke","dianwei","yase"],
    when:"纯净苍穹的进阶版，主动解控+减伤，对抗控制与爆发阵容的终极保命装。" },
  { id:"riyuan", name:"日渊", category:"物理", tag:"进阶输出", price:4180,
    stats:["+100 物理攻击","+15% 暴击率","+5% 移速"],
    passives:[{ name:"精准", desc:"普攻附带额外物理伤害。" }],
    active:{ name:"日渊", desc:"提升射程与移速，普攻分裂攻击周围敌人。" },
    compose:["逐日之弓","风暴巨剑"], heroes:["houyi","jialuo","huangzhong","luban7"],
    when:"逐日之弓的进阶版，主动开启后普攻分裂，站桩射手后期收割神器。" },
  { id:"pomodao", name:"破魔刀", category:"物理", tag:"半肉", price:2300,
    stats:["+100 物理攻击","+500 最大生命"],
    passives:[{ name:"破魔", desc:"基于自身物理攻击获得额外法术防御。" }],
    active:null, compose:["风暴巨剑","红玛瑙"], heroes:["kai","yase","dianwei","xiangyu"],
    when:"面对法师爆发时的半肉物理装，攻击越高魔抗越足。" },
  { id:"zhumengzhufeng", name:"铸梦·逐风", category:"物理", tag:"攻速", price:2100,
    stats:["+70 物理攻击","+15% 攻击速度","+10% 冷却缩减"],
    passives:[{ name:"逐风", desc:"使用技能后获得大量攻速，持续 3 秒。" }],
    active:null, compose:["风暴巨剑","速击之枪"], heroes:["sunshangxiang","sunwukong","direnje","laixiao"],
    when:"技能接普攻型物理英雄，技能后攻速爆发，前期节奏快。" },
  { id:"zhumengpofeng", name:"铸梦·破空", category:"物理", tag:"控制", price:2100,
    stats:["+70 物理攻击","+5% 冷却缩减","+500 最大生命"],
    passives:[], active:{ name:"破空", desc:"向指定方向释放冲击，击退路径上的敌人。" },
    compose:["风暴巨剑","红玛瑙"], heroes:["houyi","gongsunli","direnje","marke"],
    when:"射手/战士的主动击退保命装，被切入时推开刺客拉开距离。" },
  { id:"lingxihufu", name:"灵犀护符", category:"物理", tag:"攻速移速", price:2130,
    stats:["+60 物理攻击","+20% 攻击速度","+5% 移速"],
    passives:[{ name:"灵犀", desc:"技能命中提升移速，持续 2 秒。" }],
    active:null, compose:["雷鸣刃","速击之枪"], heroes:["marke","gongsunli","gongsunli","machao"],
    when:"需要攻速与机动性的物理英雄，技能命中风筝拉扯。" },
  { id:"poxiaozhiren", name:"破晓之刃", category:"物理", tag:"穿透", price:2000,
    stats:["+30 物理攻击","+15% 攻击速度","+10% 移速"],
    passives:[{ name:"破甲", desc:"获得 20% 物理穿透。" }],
    active:null, compose:["穿云弓","铁剑"], heroes:["houyi","luban7","sunshangxiang"],
    when:"穿云弓的进阶穿透装，前期性价比高的打坦选择。" },
  { id:"hanshuangxiqin", name:"寒霜袭侵", category:"物理", tag:"减速", price:2040,
    stats:["+80 物理攻击","+500 最大生命"],
    passives:[{ name:"寒霜", desc:"普攻命中减少目标攻速与移速。" }],
    active:null, compose:["风暴巨剑","布甲"], heroes:["dianwei","kai","yase","laofuzi"],
    when:"克制攻速射手与战士对拼，普攻附带减速减攻速。" },
  { id:"longlilijian", name:"龙鳞利剑", category:"物理", tag:"真伤", price:2100,
    stats:["+60 物理攻击","+15% 攻击速度"],
    passives:[{ name:"龙鳞", desc:"普攻附带基于目标生命的真实伤害。" }],
    active:null, compose:["雷鸣刃","速击之枪"], heroes:["lvbu","dianwei","sunwukong"],
    when:"普攻型物理英雄的进阶输出装，真伤打坦效率高。" },
  { id:"zhuiliezhiren", name:"追猎之刃", category:"物理", tag:"攻速", price:2050,
    stats:["+60 物理攻击","+20% 攻击速度"],
    passives:[{ name:"追猎", desc:"普攻命中提升移速与攻速。" }],
    active:null, compose:["雷鸣刃","速击之枪"], heroes:["cang","hanxin","marke","gongsunli"],
    when:"追击型打野与射手，击杀后持续加速收割。" },
  { id:"qianchuiduan", name:"千锤锻", category:"物理", tag:"半肉", price:2000,
    stats:["+50 物理攻击","+800 最大生命"],
    passives:[{ name:"千锤", desc:"技能命中叠加攻击力，叠满后大幅提升。" }],
    active:null, compose:["铁剑","红玛瑙"], heroes:["dianwei","kai","yase","zhaoyun"],
    when:"技能频次高的战士半肉装，越打攻击越高。" },
  { id:"bingshuangmaochang", name:"冰霜长矛", category:"物理", tag:"减速", price:1900,
    stats:["+60 物理攻击","+500 最大生命"],
    passives:[{ name:"冰霜", desc:"普攻命中减速目标。" }],
    active:null, compose:["铁剑","红玛瑙"], heroes:["guanyu","damo","lianpo","sunce"],
    when:"留人型战士/坦克，普攻减速黏住敌方核心。" },

  /* ---- 法术成品 ---- */
  { id:"ningbingzhixi", name:"凝冰之息", category:"法术", tag:"减速", price:1800,
    stats:["+120 法术攻击","+500 最大生命"],
    passives:[{ name:"凝冰", desc:"技能命中减速目标，持续 2 秒。" }],
    active:null, compose:["元素杖","红玛瑙"], heroes:["wangzhaojun","zhenji","zhouyu","xiaoqiao"],
    when:"持续控制/消耗型法师，技能减速留人，配合冰冻控制更稳。" },
  { id:"pojiaozhiyi", name:"破茧之衣", category:"法术", tag:"半肉", price:2140,
    stats:["+160 法术攻击","+800 最大生命"],
    passives:[{ name:"破茧", desc:"距离敌人越近，受到的法术伤害越低。" }],
    active:null, compose:["大棒","红玛瑙"], heroes:["diaochan","change","miyue","shangguanyuer"],
    when:"贴脸作战法师的半肉装，近身减伤配合法刺打法。" },
  { id:"yueshen", name:"月神", category:"法术", tag:"进阶保命", price:4100,
    stats:["+200 法术攻击","+10% 冷却缩减"],
    passives:[], active:{ name:"月神", desc:"进入无敌状态 1.5 秒并获得移速，期间可移动。" },
    compose:["辉月","大棒"], heroes:["diaochan","shangguanwaner","zhugeliang","daji"],
    when:"辉月的进阶版，无敌期间可移动，法师后期终极保命装。" },
  { id:"chilifazhang", name:"炽灵法杖", category:"法术", tag:"灼烧", price:2200,
    stats:["+180 法术攻击","+5% 移速"],
    passives:[{ name:"炽灵", desc:"技能命中造成持续灼烧伤害。" }],
    active:null, compose:["大棒","魔道之石"], heroes:["zhouyu","bianque","milaidi","wangzhaojun"],
    when:"持续输出型法师，技能命中叠加灼烧，磨血打坦高效。" },
  { id:"youmengfazhang", name:"幽梦法杖", category:"法术", tag:"减速", price:2200,
    stats:["+180 法术攻击","+5% 冷却缩减"],
    passives:[{ name:"幽梦", desc:"技能命中降低目标移速与回血。" }],
    active:null, compose:["大棒","圣者法典"], heroes:["xishi","zhenji","haiyue","nvwa"],
    when:"控制留人型法师，技能减速并压制敌方回复。" },
  { id:"yongyefazhang", name:"永夜法杖", category:"法术", tag:"斩杀", price:2200,
    stats:["+200 法术攻击"],
    passives:[{ name:"永夜", desc:"对生命值低于 40% 的目标造成额外伤害。" }],
    active:null, compose:["大棒","大棒"], heroes:["zhugeliang","shangguanwaner","anqila","daji"],
    when:"收割型爆发法师，斩杀残血提升爆发上限。" },
  { id:"suhuifazhang", name:"溯洄法杖", category:"法术", tag:"法强", price:2100,
    stats:["+160 法术攻击","+10% 冷却缩减"],
    passives:[{ name:"溯洄", desc:"技能命中叠加法强，脱战后重置。" }],
    active:null, compose:["大棒","圣者法典"], heroes:["wuzetian","ganjiangmoye","nvwa","shenmengxi"],
    when:"技能频次高的法师，持续命中堆叠法强越打越疼。" },
  { id:"jimiefaqiu", name:"寂灭法球", category:"法术", tag:"斩杀", price:2200,
    stats:["+200 法术攻击"],
    passives:[{ name:"寂灭", desc:"技能命中生命值低于 30% 的目标时造成额外斩杀伤害。" }],
    active:null, compose:["大棒","大棒"], heroes:["daji","anqila","xiaoqiao","wuzetian"],
    when:"爆发法师的收割补强，一套带走残血更稳。" },

  /* ---- 防御成品 ---- */
  { id:"yongyeshouhu", name:"永夜守护", category:"防御", tag:"法抗", price:2300,
    stats:["+1000 最大生命","+200 法术防御"],
    passives:[{ name:"永夜", desc:"受到法术伤害后回复生命，冷却 5 秒。" }],
    active:null, compose:["神隐斗篷","红玛瑙"], heroes:["zhangfei","niumo","baiqi","kai"],
    when:"魔女斗篷的进阶法抗装，受法伤回血持续抗压。" },
  { id:"lindong", name:"凛冬", category:"防御", tag:"物抗", price:2300,
    stats:["+1000 最大生命","+200 物理防御"],
    passives:[{ name:"凛冬", desc:"受到物理伤害时对周围敌人造成减速与伤害。" }],
    active:null, compose:["守护者之铠","红玛瑙"], heroes:["xiangyu","baiqi","lianpo","chengyaojin"],
    when:"极寒风暴的进阶物抗装，受击冰爆分割战场。" },
  { id:"shushuangcangdun", name:"舒爽苍盾", category:"防御", tag:"护盾", price:2100,
    stats:["+800 最大生命","+150 物理防御","+150 法术防御"],
    passives:[{ name:"苍盾", desc:"受到致命伤害时生成护盾并提升双抗。" }],
    active:null, compose:["红玛瑙","布甲"], heroes:["sulie","zhangfei","niumo","xiangyu"],
    when:"坦克辅助的进阶护盾装，残血自动护盾更耐打。" },
  { id:"panshihujia", name:"磐石护甲", category:"防御", tag:"减伤", price:2100,
    stats:["+900 最大生命","+200 物理防御"],
    passives:[{ name:"磐石", desc:"受到伤害时叠加减伤，叠满后大幅减伤。" }],
    active:null, compose:["红玛瑙","布甲"], heroes:["baiqi","chengyaojin","zhubajie","lianpo"],
    when:"肉坦抗伤装，持续承伤叠减伤，站得更久。" },
  { id:"yumopifeng", name:"御魔披风", category:"防御", tag:"法抗", price:2100,
    stats:["+900 最大生命","+200 法术防御"],
    passives:[{ name:"御魔", desc:"受到法术伤害时减免部分伤害。" }],
    active:null, compose:["红玛瑙","抗魔披风"], heroes:["zhangfei","niumo","kai","xiangyu"],
    when:"坦克/战士应对法师爆发，承伤免伤更稳定。" },
  { id:"fusuruanjia", name:"复苏软甲", category:"防御", tag:"回复", price:2100,
    stats:["+1000 最大生命"],
    passives:[{ name:"复苏", desc:"脱战持续回复生命，战斗中技能命中恢复部分生命。" }],
    active:null, compose:["力量腰带"], heroes:["chengyaojin","zhubajie","baiqi","sulie"],
    when:"高回复坦克的进阶装，脱战回血配合技能续航。" },
  { id:"jingjizhongkai", name:"荆棘重铠", category:"防御", tag:"反伤", price:2100,
    stats:["+500 最大生命","+300 物理防御"],
    passives:[{ name:"荆棘", desc:"受到物理伤害时反弹伤害并降低攻击者吸血。" }],
    active:null, compose:["荆棘护手","布甲"], heroes:["dianwei","xiangyu","kai","fanshangjia"],
    when:"反伤刺甲的进阶版，物理刺客克星。" },
  { id:"hanshuanghujia", name:"寒霜护甲", category:"防御", tag:"减速", price:2100,
    stats:["+800 最大生命","+220 物理防御"],
    passives:[{ name:"寒霜", desc:"受到普攻时减速攻击者并降低其攻速。" }],
    active:null, compose:["守护者之铠","红玛瑙"], heroes:["baiqi","xiangyu","lianpo","zhangfei"],
    when:"克制攻速射手的进阶物抗装，受击减速黏住。" },
  { id:"wanlingshouhu", name:"万灵守护", category:"防御", tag:"群体护盾", price:2300,
    stats:["+1000 最大生命","+200 物理防御","+200 法术防御"],
    passives:[{ name:"万灵", desc:"生命值低于 30% 时为周围友军提供护盾。" }],
    active:null, compose:["舒爽苍盾","红玛瑙"], heroes:["zhangfei","niumo","baiqi","sulie"],
    when:"坦克辅助的进阶团队装，残血群体护盾保护后排。" },
  { id:"nulongjiandun", name:"怒龙剑盾", category:"防御", tag:"伤害", price:2200,
    stats:["+800 最大生命","+220 物理防御"],
    passives:[{ name:"怒龙", desc:"技能命中造成基于生命的额外伤害。" }],
    active:null, compose:["守护者之铠","红玛瑙"], heroes:["lianpo","xiangyu","baiqi","sikongzhen"],
    when:"半肉战士的进阶装，抗伤同时补充技能伤害。" },

  /* ---- 打野成品 ---- */
  { id:"jurenzhiwo", name:"巨人之握", category:"打野", tag:"肉刀", price:2300,
    stats:["+1000 最大生命","+30 移动速度"],
    passives:[{ name:"狩猎", desc:"击杀野怪叠加生命与减伤，惩戒对野怪造成真实伤害。" }],
    active:null, compose:["巡守利斧","力量腰带"], heroes:["dianwei","zhaoyun","peiqinhu","aguduo"],
    when:"巡守利斧的进阶版，越刷越肉，半肉打野后期首选。" },

  /* ---- 游走成品 ---- */
  { id:"zhaojianzhidun", name:"昭鉴之盾", category:"游走", tag:"进阶视野", price:2100,
    stats:["+800 最大生命","+200 物理防御","+200 法术防御"],
    passives:[{ name:"奉献", desc:"附近队友获得双抗加成。" }],
    active:{ name:"觅形", desc:"探测周围视野并减速隐身单位。" },
    compose:["形昭之鉴","布甲"], heroes:["zhongkui","guiguzi","dunshan","sulie"],
    when:"形昭之鉴的进阶版，主动探视野+双抗光环，克制隐身阵容。" },
  { id:"shouhuzhidun", name:"守护之盾", category:"游走", tag:"进阶护盾", price:2100,
    stats:["+800 最大生命","+200 物理防御","+200 法术防御"],
    passives:[{ name:"奉献", desc:"附近队友获得双抗加成。" }],
    active:{ name:"救援", desc:"为周围生命值最低的队友提供护盾。" },
    compose:["救赎之翼","布甲"], heroes:["caiwenji","zhangfei","yaoling","sangqi"],
    when:"救赎之翼的进阶版，主动护盾+双抗光环，保人能力拉满。" },
  { id:"xunjieguanghuan", name:"迅捷光环", category:"游走", tag:"光环·攻速", price:1900,
    stats:["+800 最大生命","+500 最大法力"],
    passives:[{ name:"游击", desc:"附近队友获得攻速与移速加成。" }],
    active:null, compose:["凤鸣指环","布甲"], heroes:["sunbin","zhangfei","daqiao","caiwenji"],
    when:"极影的姊妹光环装，提升团队攻速与机动。" },
  { id:"zhiyuguanghuan", name:"治愈光环", category:"游走", tag:"光环·回复", price:1900,
    stats:["+800 最大生命","+500 最大法力"],
    passives:[{ name:"奉献", desc:"附近队友获得生命回复加成。" }],
    active:null, compose:["凤鸣指环","提神水晶"], heroes:["caiwenji","sangqi","yaoling","zhuangzhou"],
    when:"辅助的回血光环装，提升团队续航能力。" },
  { id:"yufangguanghuan", name:"御防光环", category:"游走", tag:"光环·双抗", price:1900,
    stats:["+800 最大生命","+500 最大法力"],
    passives:[{ name:"奉献", desc:"附近队友获得双抗加成。" }],
    active:null, compose:["鼓舞之盾","布甲"], heroes:["zhangfei","niumo","baiqi","lianpo"],
    when:"坦克辅助的双抗光环装，团队整体更抗揍。" }
];
